### ISSUE TITLE
can't see the point cloud data.

### ISSUE THREAD

**Issue by zhou-wenbin** [jmscslgroup/catvehicle#1]
I followed the the tutorial of "Visualizing the CAT Vehicle and Velodyne with rviz", but I was not able to see any point cloud data. I could only see the vehicle itself.  Do you have any clues?

**Comment by rahulbhadani** [comment]
Do you happen to have any object in from of the car?
What launch files did you use?

Try the following in three different terminals:

`roslaunch catvehicle catvehicle_neighborhood.launch`

`gzclient`

`rosrun rviz rviz`

In rviz, choose **world** as the fixed frame and add point-cloud display type with topic name `/catvehicle/lidar_points` in rviz.

Your rviz visualization should look like this:

![image](https://user-images.githubusercontent.com/8680176/99141209-40938100-2606-11eb-817c-4be58747c53b.png)

Make sure to check out the latest code from the GitHub repo.

Use rviz config file from https://github.com/jmscslgroup/catvehicle/blob/melodic_gazebo-9/config/catvehicle.rviz
