### ISSUE TITLE
Confusion about wheel-base and wheel tread

### ISSUE THREAD

**Issue by NovoG93** [jmscslgroup/catvehicle#11]
Hello again,

### Wheelbase 
in the [comment in the xacro file](https://github.com/jmscslgroup/catvehicle/blob/1db80fa0e9371117906d542b6496f8046456574b/urdf/catvehicle.xacro#L67)  you state that the wheelbase is __2.8232111 m__, in the [file that computes the velocities for the driven wheels](https://github.com/jmscslgroup/catvehicle/blob/1db80fa0e9371117906d542b6496f8046456574b/src/cmdvel2gazebo.py#L58)  you state that it is __2.62 m__ which is also used in the [distanceEstimatorSteeringbased.cpp](https://github.com/jmscslgroup/catvehicle/blob/1db80fa0e9371117906d542b6496f8046456574b/src/distanceEstimatorSteeringBased.cpp#L61) and when I run `rosservice call /gazebo/get_link_state "link_name: 'catvehicle::back_left_wheel_link' reference_frame: 'catvehicle::front_left_wheel_link'"` (on a paused simulation, before the joints are moved by the car bouncing around) i get __2.6 m__

### Wheel tread
For the wheel trad I receive a different value for the front and rear wheels using the gazebo service:
#### Front
`rosservice call /gazebo/get_link_state "link_name: 'catvehicle::back_right_wheel_link'
reference_frame: 'catvehicle::back_left_wheel_link'"`-> __1.53 m__
#### Back
`rosservice call /gazebo/get_link_state "link_name: 'catvehicle::front_right_wheel_link'
reference_frame: 'catvehicle::front_left_wheel_link'"` -> __1.49 m__ 
But in [cmdvel2gazebo](https://github.com/jmscslgroup/catvehicle/blob/1db80fa0e9371117906d542b6496f8046456574b/src/cmdvel2gazebo.py#L66) it is set to __1.29 m__

**Comment by rahulbhadani** [comment]
Yeah, I should remove the comment as that value of 2.8232111 m was nowhere used.

**Comment by NovoG93** [comment]
And what about the wheel tread?
What are the real values? The values from the gazebo service?

**Comment by rahulbhadani** [comment]
yes, front and back wheel tread doesn't necessarily have to be the same.
