### ISSUE TITLE
Vehicle could not go forward

### ISSUE THREAD

**Issue by kadirtunc** [jmscslgroup/catvehicle#2]
I am using ros melodic. Ubuntu 18.04

Car moves backward successfully but it can not go forward. Please help me

**Comment by rahulbhadani** [comment]
@kadirtunc When you are raising an issue, you need to provide detailed information about your issue.

**Comment by kadirtunc** [comment]
OK. Which information do you need?

**Comment by kadirtunc** [comment]
I wrote this file for send messages to these topics.




#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Twist


pub = rospy.Publisher('/catvehicle/cmd_vel_safe', Twist, queue_size=10)
pub2 = rospy.Publisher('/catvehicle/cmd_vel', Twist, queue_size=10)
pub3 = rospy.Publisher('/catvehicle/vel', Twist, queue_size=10)
rospy.init_node("velfrompython",anonymous=True)
rate = rospy.Rate(10)
i=0
if __name__ == "__main__":
    while not rospy.is_shutdown():
        move_cmd = Twist()
        move_cmd.linear.x = 10.0
        print(move_cmd)
        pub3.publish(move_cmd)
        pub2.publish(move_cmd)
        pub.publish(move_cmd)
        rate.sleep()
        i=i+1

It works actually. When I change move_cmd.linear.x to negative it goes backwards. But when I changed it to positive it does not work

**Comment by rahulbhadani** [comment]
@kadirtunc Thanks for an interest in the CAT Vehicle simulator.

You can only publish on `/catvehicle/cmd_vel` topics. Some tutorials can be found out on https://cps-vo.org/group/CATVehicleTestbed/wiki

Further, please look at some guidelines on how to ask questions

https://stackoverflow.com/help/how-to-ask

**Comment by kadirtunc** [comment]
Thanks for your answer. I'll do better my next question. 

But I do not understand, I modified hardLeft.bagy file for just go forward. I change angular.z to 0.0. It works correctly. But where is my problem? 
I delete other unnecessary topics and run it. It could not work. It just goes backwards.

  ```
#!/usr/bin/env python
  
  import rospy
  from geometry_msgs.msg import Twist
  
  
  pub2 = rospy.Publisher('/catvehicle/cmd_vel', Twist, queue_size=100)
  rospy.init_node("velfrompython",anonymous=True)
  rate = rospy.Rate(100)
  i=0
  if __name__ == "__main__":

    while not rospy.is_shutdown():
        move_cmd = Twist()
        **move_cmd.linear.x = -1.0**
        pub2.publish(move_cmd)
        rate.sleep()
        i=i+1`
```
works

``` 
#!/usr/bin/env python
  
  import rospy
  from geometry_msgs.msg import Twist
  
  
  pub2 = rospy.Publisher('/catvehicle/cmd_vel', Twist, queue_size=100)
  rospy.init_node("velfrompython",anonymous=True)
  rate = rospy.Rate(100)
  i=0
  if __name__ == "__main__":

    while not rospy.is_shutdown():
        move_cmd = Twist()
        **move_cmd.linear.x = 1.0**
        pub2.publish(move_cmd)
        rate.sleep()
        i=i+1

```
does not work

**Comment by kadirtunc** [comment]
Hello again. When I send forward command to cmd_vel_safe topic it goes forward but It stops every 20ms. How can I solve this issue?

**Comment by rahulbhadani** [comment]
@kadirtunc With incomplete information about your simulation run, there is no way for me to know how did you start the simulation.

What launch file did you execute? Did your spawn service fail? Did you do diagnostics in terms of checking with `rostopic list`, `rostopic echo`, `rosnode list`, `rosnode info`? 

One way to run the simulation is by following:

Terminal 1:
`roslaunch catvehicle catvehicle_empty.launch`

Terminal 2:
`roslaunch catvehicle catvehicle_spawn.launch`

And then you can test it by sending velocity command from command line:
Terminal 3:
```
rostopic pub -r 10 /catvehicle/cmd_vel geometry_msgs/Twist "linear:
  x: 1.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 

```

If your spawn service fails for some reason - mostly it fails on the slow machine when you don't have enough RAM to allocate to processes - you won't see your car moving.

The code you provided works the above sequence of launch file execution.

There are many launch files in the CAT Vehicle ROS package. They all have different purposes, and they take different command-line arguments.

Again, please read the guidelines on how to ask for help by providing sufficient information and a minimum viable example that reproduces your issue.

**Comment by kadirtunc** [comment]
Thank you. I solved my problem.
And I am sorry. I will do better at the next question

**Comment by rahulbhadani** [comment]
Thanks, @kadirtunc . I am in the process of creating documentation. Please checkout the page https://jmscslgroup.github.io/catvehicle/ at a later date.
