### ISSUE TITLE
catvehicle_skidpan urdf spawn fail

### ISSUE THREAD

**Issue by kadirtunc** [jmscslgroup/catvehicle#3]
Hi everyone. I watched Jonathan Sprinkle's rviz visualize video. When I want to add RobotModel, it just adds sensors, not model. 

When I look at the command line while skidpan launch file loading, I get this error.

[INFO] [1616678881.408235, 1089.346000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name catvehicle
[ERROR] [1616678881.409398, 1089.346000]: Spawn service failed. Exiting.
[ INFO] [1616678881.423752592, 1089.346000000]: Physics dynamic reconfigure ready.
[catvehicle/urdf_spawnercatvehicle-2] process has died [pid 12118, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -x 1 -y 1 -z 0 -urdf -model catvehicle -param robot_description __name:=urdf_spawnercatvehicle __log:=/home/kadir/.ros/log/fa1909d0-8d51-11eb-aa58-e82a44f292f1/catvehicle-urdf_spawnercatvehicle-2.log].
log file: /home/kadir/.ros/log/fa1909d0-8d51-11eb-aa58-e82a44f292f1/catvehicle-urdf_spawnercatvehicle-2*.log
[ INFO] [1616678881.789254929, 1089.346000000]: Camera Plugin: Using the 'robotNamespace' param: '/catvehicle'

I did launch catvehicle_skidpan.launch without arguments. So I did not change anything.

I am using Ubuntu 18.04 ROS Melodic

I hope I give to enough information.

**Comment by rahulbhadani** [comment]
Unfortunately, that is an issue related to spawning service and not specific to the CAT Vehicle package. You may need to keep trying until the spawn service succeeds. Alternatively, you can launch `catvehicle_empty.launch` and then launch `catvehicle_spawn.launch` in another terminal.
