### ISSUE TITLE
Branch Noetic missing argument updateRate and old xacro.py command

### ISSUE THREAD

**Issue by NovoG93** [jmscslgroup/catvehicle#8]
Hello,

__System__
* OS: Ubuntu 20.04
* ROS: Noetic

basically in all launch files that spawn the car the argument `updateRate` is missing, further the old _xacro.py_ is used (which is not available in noetic) instead of the new _xacro_.

E.g. see: [catvehicle_canyonview.launch](https://github.com/jmscslgroup/catvehicle/blob/noetic_gazebo-11/launch/catvehicle_canyonview.launch#L51) or [catvehicle_custom.launch](https://github.com/jmscslgroup/catvehicle/blob/noetic_gazebo-11/launch/catvehicle_custom.launch#L62)

**Comment by rahulbhadani** [comment]
@NovoG93 Thank you for bringing this to our attention. I pushed a few changes a couple of days ago and it was not reflected in the rest of the launch file. I will push some updates in the next few hours.

**Comment by rahulbhadani** [comment]
Fixed in commit de59049
